name: Deploy all Pages to GitHub Pages

on:
  workflow_dispatch:

env: 
  PREFIX: landing-pages-11ty-poc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.page }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        page:
          - test-app
          - test-2-app
          - travel-insurance-a1
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ env.PREFIX }}-${{ matrix.page }}
          event-type: build-and-deploy