name: Deploy specific Page to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      page:
        description: 'Name of the page to build & deploy'
        required: true

env: 
  PREFIX: landing-pages-11ty-poc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.page }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ env.PREFIX }}-${{ github.event.inputs.page }}}
          event-type: build-and-deploy